//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleData.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScheduleData.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All conflicts.
        /// </summary>
        public static string ConflictCriteriaAll {
            get {
                return ResourceManager.GetString("ConflictCriteriaAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card has not filled fields.
        /// </summary>
        public static string ConflictCriteriaCardsWithBlankFields {
            get {
                return ResourceManager.GetString("ConflictCriteriaCardsWithBlankFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group is in different classrooms at the same time.
        /// </summary>
        public static string ConflictCriteriaGroupsInDifferentClassrooms {
            get {
                return ResourceManager.GetString("ConflictCriteriaGroupsInDifferentClassrooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lecturer is in different classrooms at the same time.
        /// </summary>
        public static string ConflictCriteriaLecturersInDifferentClassrooms {
            get {
                return ResourceManager.GetString("ConflictCriteriaLecturersInDifferentClassrooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lecturer is on different classes at the same time.
        /// </summary>
        public static string ConflictCriteriaLecturersOnDifferentClasses {
            get {
                return ResourceManager.GetString("ConflictCriteriaLecturersOnDifferentClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than 4 classes per day.
        /// </summary>
        public static string ConflictCriteriaMoreThanFourClassesPerDay {
            get {
                return ResourceManager.GetString("ConflictCriteriaMoreThanFourClassesPerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusted classes have different addresses.
        /// </summary>
        public static string ConflictCriteriaNextClassesAtDifferentAddress {
            get {
                return ResourceManager.GetString("ConflictCriteriaNextClassesAtDifferentAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New group.
        /// </summary>
        public static string GroupNewName {
            get {
                return ResourceManager.GetString("GroupNewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New specialization.
        /// </summary>
        public static string SpecializationNewName {
            get {
                return ResourceManager.GetString("SpecializationNewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New year.
        /// </summary>
        public static string YearOfStudyNewName {
            get {
                return ResourceManager.GetString("YearOfStudyNewName", resourceCulture);
            }
        }
    }
}
